<?php
// $Id: vk_share.module,v 1.3 2010/10/06 19:35:51 romka Exp $

/**
 * Implementation of hook_perm().
 */
function vk_share_perm() {
  return array('use vkontakte share button');
}

/**
 * Implementation of hook_menu().
 */
function vk_share_menu() {
  $items['admin/settings/vk_share'] = array(
    'title' => 'VKontakte share-button settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('vk_share_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'vk_share.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_link().
 */
function vk_share_link($type, $object, $teaser = FALSE) {
  $links = array();
  if ($type == 'node') {
    $node_types = variable_get('vk_share_node_types', array('page' => 'page'));
    $access = user_access('use vkontakte share button');
    if ($node_types[$object->type] && $access) {      
      $type = variable_get('vk_share_button_style', 'button_count');
      

      $text = preg_replace("!<script(.*?)</script>!si", "", $object->teaser);
      $text = str_replace("\n", "", $text);
      $text = str_replace('"', '\"', $text);
      $text = strip_tags($text);
      $text = trim($text);

      if ((!$teaser && variable_get('vk_share_display_page', 1)) || ($teaser && variable_get('vk_share_display_teaser', 1))) {
      //if (!$teaser && variable_get('vk_share_display_page', 1)) {
        drupal_add_css(drupal_get_path('module', 'vk_share') . '/vk_share.css');

        switch($type) {
          case 'button_count':
            $links['vk_share_link'] = array(
              'title' => '<script type="text/javascript"><!--
document.write(VK.Share.button({url:"' . url('node/'. $object->nid, array('absolute' => TRUE)) . '", title:"' . $object->title . '", description: "' . $text . '"},{type: "round", text: "Сохранить"}));
--></script>',
              'html' => TRUE,
            );
            break;
          case 'button':
            $links['vk_share_link'] = array(
              'title' => '<script type="text/javascript"><!--
document.write(VK.Share.button({url:"' . url('node/'. $object->nid, array('absolute' => TRUE)) . '", title:"' . $object->title . '", description: "' . $text . '"},{type: "round_nocount", text: "Сохранить"}));
--></script>',
              'html' => TRUE,
            );
            break;
          case 'link':
            $links['vk_share_link'] = array(
              'title' => '<script type="text/javascript"><!--
document.write(VK.Share.button({url:"' . url('node/'. $object->nid, array('absolute' => TRUE)) . '", title:"' . $object->title . '", description: "' . $text . '"},{type: "link", text: "Сохранить"}));
--></script>',
              'html' => TRUE,
            );
            break;
        }
      }
      /*
      elseif ($teaser && variable_get('vk_share_display_teaser', 1)) {
        drupal_add_css(drupal_get_path('module', 'vk_share') . '/vk_share.css');
        switch($type) {
          case 'button_count':
            $links['vk_share_link'] = array(
              'title' => '<script type="text/javascript"><!--
document.write(VK.Share.button({url:"' . url('node/'. $object->nid, array('absolute' => TRUE)) . '", title:"' . $object->title . '", description: "' . $text . '"},{type: "round", text: "Сохранить"}));
--></script>',
              'html' => TRUE,
            );
            break;
          case 'button':
            $links['vk_share_link'] = array(
              'title' => '<script type="text/javascript"><!--
document.write(VK.Share.button({url:"' . url('node/'. $object->nid, array('absolute' => TRUE)) . '", title:"' . $object->title . '", description: "' . $text . '"},{type: "round_nocount", text: "Сохранить"}));
--></script>',
              'html' => TRUE,
            );
            break;
          case 'link':
            $links['vk_share_link'] = array(
              'title' => '<script type="text/javascript"><!--
document.write(VK.Share.button({url:"' . url('node/'. $object->nid, array('absolute' => TRUE)) . '", title:"' . $object->title . '", description: "' . $text . '"},{type: "link", text: "Сохранить"}));
--></script>',
              'html' => TRUE,
            );
            break;
        }
      }
      //*/
    }
  }
  return $links;
}

/**
 * Implementation of hook_init().
 */
function vk_share_init() {
  drupal_set_html_head('<script type="text/javascript" src="http://vkontakte.ru/js/api/share.js?9" charset="windows-1251"></script>');
}
