#!/bin/bash 

source `dirname $0`/config.inc

DATE=`date +\%Y\%m\%d\%H\%M`
DRUPALDUMPNAME=$BACKUP_FOLDER/$DB_CHGK_DRUPAL_NAME.$DATE.sql
DUMPNAME=$BACKUP_FOLDER/$DB_CHGK_NAME.$DATE.sql
if [ ! -d $BACKUP_FOLDER ] 
  then 
    echo -n Backup folder  does not exist. Creating...
    mkdir $BACKUP_FOLDER
    source $SETUP_FOLDER/check_success "Can not create $BACKUP_FOLDER";
fi

echo -n Dumping chgk_drupal...
$MYSQLDUMP_EXECUTABLE_FULL $DB_CHGK_DRUPAL_NAME >$DRUPALDUMPNAME
source $SETUP_FOLDER/check_success "Can not dump $DB_CHGK_DRUPAL_NAME to $DRUPALDUMPNAME";

echo -n Dumping chgk...
$MYSQLDUMP_EXECUTABLE_FULL $DB_CHGK_NAME >$DUMPNAME
source $SETUP_FOLDER/check_success "Can not dump $DB_CHGK_NAME to $DUMPNAME";

echo -n gzipping chgk_drupal...
gzip $DRUPALDUMPNAME
source $SETUP_FOLDER/check_success "Can not gzip $DRUPALDUMPNAME";

echo -n gzipping chgk...
gzip $DUMPNAME
source $SETUP_FOLDER/check_success "Can not gzip $DUMPNAME";


